stages:
  - build
  - lint
  - test
  - deploy
  - cleanup

variables:
  HELM: "helm3"
  REPO_URL: http://repo-staging.dc.prozorro.gov.ua/repos/helm/

build:
  stage: build
  tags:
    - shell
  rules:
    # exclude schedules
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    # if it is a tag
    - if: $CI_COMMIT_TAG
      variables:
        CI_TAG: $CI_COMMIT_TAG
    # if it is a default branch (for example master)
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        CI_TAG: "latest"
    # if it is push event or manual pipeline trigger (merge request is excluded)
    - if: $CI_PIPELINE_SOURCE != "merge_request_event"
      variables:
        CI_TAG: "ci-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA"
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build --build-arg version=$(git describe --tags) -t $CI_REGISTRY_IMAGE:$CI_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CI_TAG
  after_script:
    - echo "CI_TAG=$CI_TAG" >> build.env
  artifacts:
    reports:
      dotenv: build.env

.image_defaults:
  image:
    name: $CI_REGISTRY_IMAGE:$CI_TAG
  before_script:
    - uv sync --frozen --no-cache $UV_EXTRA_ARGS --compile-bytecode

.lint_tools:
  extends: .image_defaults
  allow_failure: false
  tags:
    - kube-dev
  only:
    - branches
  except:
    - schedules
  stage: lint
  variables:
    GIT_STRATEGY: clone

mypy:
  extends: .lint_tools
  script:
    - uv run --active mypy src/ --explicit-package-bases

ruff:
  extends: .lint_tools
  script:
    - uv run --active ruff check --force-exclude

test:
  extends: .image_defaults
  stage: test
  services:
    - name: bitnamilegacy/mongodb:6.0.13-debian-11-r9
      alias: mongo
  variables:
    SWAGGER_DOC_AVAILABLE: ""
    AUTH_PATH: ${CI_PROJECT_DIR}/auth.ini
    IMG_DIR: ${CI_PROJECT_DIR}/images
    MONGODB_URI: mongodb://root:example@mongo:27017/?replicaSet=rs0
    MONGODB_URL: mongodb://root:example@mongo:27017/?replicaSet=rs0
    MONGODB_ROOT_PASSWORD: example
    MONGODB_REPLICA_SET_MODE: primary
    MONGODB_REPLICA_SET_NAME: rs0
    MONGODB_REPLICA_SET_KEY: replicaSetKey
  tags:
    - kube-dev
  script:
    - uv run pytest -x -s tests
      --cov=catalog
      --cov-report xml
      --cov-report term
  artifacts:
    reports:
      coverage_report:
        path: coverage.xml
        coverage_format: cobertura
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

review:
  stage: deploy
  tags:
    - shell
  environment:
    name: review/${CI_COMMIT_REF_SLUG}
    action: start
    url: http://catalog.catalog-${CI_COMMIT_REF_SLUG}.${K8S_DOMAIN}/api/ping
    on_stop: stop_review
    auto_stop_in: 1 month
  variables:
    VERSION: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
    RELEASE: catalog-${CI_COMMIT_REF_SLUG}
  script:
    - helm3 upgrade -i ${RELEASE} helm/prozorro-catalog --namespace dev-prozorro
        --set image.tag=${CI_TAG}
        --set environment.VERSION=${VERSION}
        --set ingress.hosts[0].host=catalog.${RELEASE}.k8s.prozorro.gov.ua,ingress.hosts[0].paths[0].path=/
        --set ingress.hosts[0].paths[0].pathType=ImplementationSpecific
  only:
    - branches
  except:
    - master
    - schedules
  when: manual

run_seed:
  extends: review
  script:
    - kubectl --namespace dev-prozorro rollout status deployment ${RELEASE}-prozorro-catalog
    - kubectl --namespace dev-prozorro exec deployment/${RELEASE}-prozorro-catalog -- python -m seed
  when: manual
  except:
    - schedules

run_cron_price:
  extends: review
  script:
    - kubectl --namespace dev-prozorro rollout status deployment ${RELEASE}-prozorro-catalog
    - kubectl --namespace dev-prozorro exec deployment/${RELEASE}-prozorro-catalog -- python cron/calculate_price.py
  when: manual
  except:
    - schedules

review_master:
  extends: review
  after_script:
    - kubectl --namespace dev-prozorro rollout restart deployment catalog-master-prozorro-catalog
  only:
    - master
  except:
    - schedules

stop_review:
  stage: deploy
  script:
    - helm3 delete catalog-$CI_COMMIT_REF_SLUG --namespace dev-prozorro || true
  environment:
    name: review/${CI_COMMIT_REF_SLUG}
    action: stop
  tags:
    - shell
  only:
    - branches
  except:
    - schedules
  when: manual

clenup-ci-image:
  stage: cleanup
  tags:
    - shell
  script:
    - docker rmi -f $CI_TAG || true
  when: always
