services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UV_EXTRA_ARGS: ""
    command: [
      "gunicorn",
      "catalog.api:application",
      "--bind",
      "0.0.0.0:8000",
      "--worker-class",
      "aiohttp.GunicornWebWorker",
      "--reload",
      "--graceful-timeout=60",
      "--timeout=3600",
    ]
    environment:
      MONGODB_URI: 'mongodb://root:example@mongo:27017/?replicaSet=rs0' 
      PYTHONUNBUFFERED: '1'
    ports:
      - 8000:8000
    volumes:
      - ./src/catalog:/app/catalog
      - ./src/cron:/app/cron
      - ./tests:/app/tests
      - ./auth.ini:/app/auth.ini
    depends_on:
      - mongo

  crawler:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UV_EXTRA_ARGS: ""
    command: ["python", "-m", "catalog.crawler"]
    environment:
      MONGODB_URI: 'mongodb://root:example@mongo:27017/?replicaSet=rs0' 
      MONGODB_URL: 'mongodb://root:example@mongo:27017/?replicaSet=rs0' 
      PYTHONUNBUFFERED: '1'
    volumes:
      - ./src/catalog:/app/catalog
      - ./src/cron:/app/cron
      - ./tests:/app/tests
      - ./auth.ini:/app/auth.ini
    depends_on:
      - mongo

  mongo:
    image: 'bitnamilegacy/mongodb:6.0.13'
    environment:
      MONGODB_ROOT_PASSWORD: example
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_REPLICA_SET_KEY: replicaSetKey
      MONGODB_ADVERTISED_HOSTNAME: mongo
    ports:
      - 27017:27017
