---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "prozorro-catalog.fullname" . }}
  labels:
    app: {{ template "prozorro-catalog.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: api
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  auth.ini: {{ tpl (.Files.Get "configs/auth.ini") . | b64enc | quote }}
